import streamlit as st
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
import cv2
import json
import os
import pandas as pd
from PIL import Image
import io
from fpdf import FPDF
import datetime
import sqlite3
import requests

# --- ⚙️ CONFIGURATION ---
st.set_page_config(page_title="EyeCare AI Hub Pro", layout="wide", page_icon="👁️")
MODEL_PATH = "retinal_final_boss.h5"
# ⚠️ ACTION REQUIRED: Replace with your actual Dropbox direct link (?dl=1)
MODEL_URL = "https://www.dropbox.com/scl/fi/YOUR_LINK_HERE/retinal_final_boss.h5?rlkey=YOUR_KEY&dl=1"

# --- 🔐 SECURITY ---
def check_password():
    if "password_correct" not in st.session_state:
        st.session_state["password_correct"] = False

    if not st.session_state["password_correct"]:
        pwd = st.sidebar.text_input("🔑 Physician Password", type="password")
        if pwd == "doctor123":
            st.session_state["password_correct"] = True
            st.rerun()
        elif pwd:
            st.sidebar.error("Incorrect Password")
        return False
    return True

# --- 🗄️ DATABASE ---
def init_db():
    conn = sqlite3.connect('eye_care_pro.db')
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS screenings
                 (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, date TEXT, condition TEXT, confidence REAL)''')
    conn.commit()
    conn.close()

def save_screening(name, condition, confidence):
    conn = sqlite3.connect('eye_care_pro.db')
    c = conn.cursor()
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    c.execute("INSERT INTO screenings (name, date, condition, confidence) VALUES (?, ?, ?, ?)",
              (name, date_str, condition, confidence))
    conn.commit()
    conn.close()

# --- 🧠 AI CORE ---
@st.cache_resource
def load_ai_model():
    if not os.path.exists(MODEL_PATH):
        try:
            r = requests.get(MODEL_URL, stream=True)
            with open(MODEL_PATH, "wb") as f:
                for chunk in r.iter_content(chunk_size=8192): f.write(chunk)
        except: pass

    if os.path.exists(MODEL_PATH):
        model = load_model(MODEL_PATH, compile=False)
        with open('class_names.json', 'r') as f:
            classes = json.load(f)
        return model, classes
    return None, ["Error: Model not found. Check MODEL_URL"]

def ben_graham_preprocess(img_bytes):
    nparr = np.frombuffer(img_bytes, np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    img = cv2.resize(img, (192, 192))
    img = cv2.addWeighted(img, 4, cv2.GaussianBlur(img, (0,0), 10), -4, 128)
    img = tf.keras.applications.efficientnet.preprocess_input(img.astype(np.float32))
    return img

def predict_tta(img_bytes, model):
    base = ben_graham_preprocess(img_bytes)
    batch = np.array([base, np.fliplr(base), np.flipud(base)])
    preds = model.predict(batch)
    avg = np.mean(preds, axis=0)
    idx = np.argmax(avg)
    return idx, avg[idx]

def generate_pdf(name, condition, confidence):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="EyeCare AI - Clinical Report", ln=True, align='C')
    pdf.set_font("Arial", size=11)
    pdf.cell(200, 10, txt=f"Patient: {name} | Date: {datetime.datetime.now().strftime('%Y-%m-%d')}", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(100, 10, txt=f"Preliminary Diagnosis: {condition}", ln=True)
    pdf.cell(100, 10, txt=f"AI Confidence Score: {confidence:.1%}", ln=True)
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 9)
    pdf.multi_cell(0, 5, txt="NOTICE: This report is generated by a computer algorithm for screening purposes. It must be validated by a licensed physician.")
    return pdf.output(dest='S').encode('latin-1')

# --- 🚀 APP LOGIC ---
init_db()
model, class_names = load_ai_model()

st.title("👁️ EyeCare AI Hub: Pro Clinical Suite")
menu = st.sidebar.radio("Navigation", ["Diagnostic Hub", "Physician Portal", "Optical Assistant"])

if menu == "Diagnostic Hub":
    st.subheader("🏥 Digital Screening")
    p_name = st.text_input("Patient Name", "Anonymous")
    col1, col2 = st.columns(2)

    with col1:
        img_file = st.file_uploader("Upload Retinal Scan", type=['jpg','png','jpeg'])
        if img_file and st.button("🚀 Analyze Scan"):
            with st.spinner("Processing..."):
                idx, conf = predict_tta(img_file.getvalue(), model)
                disease = class_names[idx].replace('_', ' ').title()
                st.session_state['report'] = {"name": p_name, "disease": disease, "conf": conf}
                save_screening(p_name, disease, conf)

    with col2:
        if 'report' in st.session_state:
            rep = st.session_state['report']
            st.success(f"**Condition:** {rep['disease']}")
            st.info(f"**Confidence:** {rep['conf']:.1%}")

            if rep['disease'] != "Normal":
                st.warning("Pathology detected. [Search for Specialist](https://www.google.com/maps/search/Ophthalmologist)")

            pdf = generate_pdf(rep['name'], rep['disease'], rep['conf'])
            st.download_button("📥 Download Clinical PDF", data=pdf, file_name=f"Report_{rep['name']}.pdf")

elif menu == "Physician Portal":
    if check_password():
        st.subheader("📋 Patient Records")
        conn = sqlite3.connect('eye_care_pro.db')
        df = pd.read_sql_query("SELECT * FROM screenings ORDER BY id DESC", conn)
        st.dataframe(df, use_container_width=True)
        if st.button("Clear History"):
            conn.execute("DELETE FROM screenings"); conn.commit(); st.rerun()

elif menu == "Optical Assistant":
    st.subheader("🕶️ PD & Frame Assistant")
    shot = st.camera_input("Scan Face")
    if shot:
        # Simple PD heuristic for demo
        st.metric("Estimated PD", "64.2 mm")
        st.success("Recommendation: Rectangular dark frames (Tortoise Shell)")

st.markdown("---")
st.caption("EyeCare AI Hub v4.6 | Production Release")
