import streamlit as st
import requests
import json
from PIL import Image
import io
from fpdf import FPDF
import datetime
from face_utils import analyze_face
import os

# Setup
API_URL = "http://127.0.0.1:8000/detect/"

def generate_pdf(res, original_img, cam_img_url):
    pdf = FPDF()
    pdf.add_page()
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Retinal AI Screening Report", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt=f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
    pdf.ln(10)
    # Diagnosis
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(100, 10, txt="AI Preliminary Findings:", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(100, 10, txt=f"Detected Condition: {res['disease'].replace('_', ' ').title()}", ln=True)
    pdf.cell(100, 10, txt=f"AI Confidence: {res['confidence']:.1%}", ln=True)
    pdf.ln(5)
    # Disclaimer
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, txt="Disclaimer: This is an automated screening result generated by a deep learning model. It is not a clinical diagnosis. Please consult a qualified ophthalmologist.")
    return pdf.output(dest='S').encode('latin-1')

st.set_page_config(
    page_title="EyeCare AI Hub",
    page_icon="👁️",
    layout="wide"
)

# Custom CSS
st.markdown("""
    <style>
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #007bff; color: white; }
    .prediction-card { padding: 20px; border-radius: 10px; background-color: white; box-shadow: 0 4px 6px rgba(0,0,0,0.1); text-align: center; }
    .confidence-high { color: #28a745; font-size: 24px; font-weight: bold; }
    .confidence-med { color: #ffc107; font-size: 24px; font-weight: bold; }
    .confidence-low { color: #dc3545; font-size: 24px; font-weight: bold; }
    </style>
    """, unsafe_allow_html=True)

# Sidebar Navigation
st.sidebar.title("🛠️ Tool Selection")
app_mode = st.sidebar.selectbox("Choose Service", ["Retinal Disease Screening", "PD & Frame Assistant"])

if app_mode == "Retinal Disease Screening":
    st.title("👁️ Retinal Disease AI Screening")
    st.markdown("---")
    col1, col2 = st.columns([1, 1])
    with col1:
        st.subheader("📤 Upload Fundus Image")
        uploaded_file = st.file_uploader("Select a JPG or PNG image of the retina", type=["jpg", "jpeg", "png"])
        if uploaded_file:
            image = Image.open(uploaded_file)
            st.image(image, caption="Original Scan", use_column_width=True)
            if st.button("🚀 Run AI Analysis"):
                with st.spinner("Analyzing retinal structures..."):
                    files = {"file": (uploaded_file.name, uploaded_file.getvalue(), uploaded_file.type)}
                    try:
                        response = requests.post(API_URL, files=files)
                        if response.status_code == 200: st.session_state['result'] = response.json()
                        else: st.error(f"Error: {response.status_code}")
                    except Exception as e: st.error(f"Connection failed: {e}")
    with col2:
        st.subheader("📊 Diagnostic Results")
        if 'result' in st.session_state:
            res = st.session_state['result']
            disease = res['disease']; conf = res['confidence']; gradcam_url = res.get('gradcam_url')
            st.markdown(f"""<div class="prediction-card"><h3>Detected Condition</h3><h2 style="color: #1a73e8;">{disease.replace('_', ' ').title()}</h2><hr><p>Confidence Level</p><p class="{'confidence-high' if conf > 0.7 else 'confidence-med' if conf > 0.4 else 'confidence-low'}">{conf:.1%}</p></div>""", unsafe_allow_html=True)
            if gradcam_url:
                st.markdown("---"); st.subheader("🔍 AI Attention Heatmap")
                full_cam_url = f"http://127.0.0.1:8000{gradcam_url}"
                st.image(full_cam_url, use_column_width=True)
                pdf_data = generate_pdf(res, None, full_cam_url)
                st.download_button(label="📥 Download Medical Report (PDF)", data=pdf_data, file_name="Retinal_Report.pdf", mime="application/pdf")

elif app_mode == "PD & Frame Assistant":
    st.title("🕶️ PD Measurement & Frame Finder")
    st.write("Upload a clear selfie to measure your Pupillary Distance and find the perfect frame shades.")
    face_file = st.file_uploader("Upload Selfie", type=["jpg", "png", "jpeg"])
    if face_file:
        temp_face = f"temp_face_{face_file.name}"
        with open(temp_face, "wb") as f: f.write(face_file.getbuffer())
        col1, col2 = st.columns(2)
        with col1: st.image(face_file, caption="Analyzing Face...", use_column_width=True)
        with col2:
            with st.spinner("Processing facial landmarks..."):
                face_data = analyze_face(temp_face)
            if face_data:
                st.success("✅ Analysis Complete")
                st.metric("Pupillary Distance (PD)", f"{face_data['pd_mm']} mm")
                st.info(f"**Detected Face Shape:** {face_data['face_shape']}")
                st.write(f"**Recommended Shades:** {face_data['recommendation']}")
            else: st.error("Could not detect a clear face. Please look directly at the camera.")
        if os.path.exists(temp_face): os.remove(temp_face)

st.markdown("---")
st.warning("⚠️ **Disclaimer:** This tool is for screening and educational purposes only. It is not a medical diagnosis.")
